services:
  app:
    build: .
    container_name: hasf-io-test-app
    hostname: hasf-io-test-app
    ports:
      - 8080:80
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100M"
    environment:
      CI_ENVIRONMENT: development

