#!/usr/bin/env sh

abort()
{
	echo "$1" 1>&2
	exit 1
}

if [ -z "$HASF_IO_ROOT_DIR" ]
then
	abort "Expecting environment variable HASF_IO_ROOT_DIR."
fi

if [ -n "HASF_IO_PRODUCTION" ]
then
	HASF_IO_BUILD_DIR="$HASF_IO_ROOT_DIR/prod"
else
	HASF_IO_BUILD_DIR="$HASF_IO_ROOT_DIR/debug"
fi

HASF_IO_BUILD_PUBLIC_DIR="$HASF_IO_BUILD_DIR/public"
HASF_IO_BUILD_APP_DIR="$HASF_IO_BUILD_DIR/app"
HASF_IO_BUILD_WRITABLE_DIR="$HASF_IO_BUILD_DIR/writable"
HASF_IO_BUILD_TESTS_DIR="$HASF_IO_BUILD_DIR/tests"
HASF_IO_BUILD_READONLY_DIR="$HASF_IO_BUILD_DIR/readonly"

cp -r "$HASF_IO_ROOT_DIR/wip" "$HASF_IO_BUILD_DIR"

export HASF_IO_BUILD_DIR HASF_IO_BUILD_PUBLIC_DIR HASF_IO_BUILD_APP_DIR HASF_IO_BUILD_WRITABLE_DIR HASF_IO_BUILD_TESTS_DIR HASF_IO_BUILD_READONLY_DIR

