project:
  name: HASF.io
  version: 1.0.0-alpha
  description: >
    Collection of simple tools created to do
    simple tasks, of a light, private, fast,
    and free way; forever!

  website:
    home-url: https://hasf.io
    host-provider:
      name: InfinityFree
      address: https://www.infinityfree.com
      plan:
        type: Shared hosting.
        price: Free.

  repository:
    version-control-software: git
    remote-url:
      - https://github.com/duckafire/HASF.io
      - https://gitlab.com/duckafire/HASF.io

  dependences:
    code:
      languages:
        server-side:
          - PHP_8
          - SH_(POSIX_2008)
          - XML_1
          - YAML_1
        client-side:
          - XHTML_5 (HTML_5 + XML_1)
          - SVG_1
          - CSS_3
          - JS_6 (ES_6 / ES_2015)
        both:
          - JSON_(RFC_8259)
      frameworks:
        server-side:
          - CodeIgniter_4 (php)
      libraries:
        server-side:
          - SymfonyYAML_8 (php)
        client-side:
          - JQuery_3 (js)
    environment:
      development:
        - Debian_11 (derivated / based) (linux)
        - Docker_23
      production:
        - Apache_2 (+mod_php)
        #- MariaDB_10

